apiVersion: v1
kind: Service
metadata:
  name: pona-webapp
  namespace: pona-webapp
spec:
  selector:
    app: pona-webapp
  ports:
    - protocol: TCP
      port: 3480
      targetPort: 3000
  type: LoadBalancer